### ISSUE TITLE
onItemSelected is triggered onload (only on android device)

### ISSUE THREAD

**Issue by js-jegan** [kalontech/ReactNativeWheelPicker#87] opened 2019-04-05 15:27 UTC
On Load, `onItemSelected` is triggered with selected position as `0`. Is there a way to stop this. I strongly recommend to have this solved.

Because of this issue, only without default selected index the picker works.

**Comment by jeffmeoi** [comment] 2019-04-13 13:21
I meet the problem too.

**Comment by Makar8000** [comment] 2019-04-19 14:37
Experiencing the same issue on RN v0.59.4

**Comment by amallo** [comment] 2019-05-03 08:33
+1

**Comment by madandrija** [comment] 2019-05-10 09:52
Duplicate of https://github.com/KalonTech/ReactNativeWheelPicker/issues/87

**Comment by ArtemKosiakevych** [comment] 2020-02-26 08:06
try to use `initPosition`

**Closed by ArtemKosiakevych** 2020-02-26 08:06 UTC
